# Generated by Django 3.2.2 on 2021-05-14 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuetracker', '0002_alter_project_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors_relation', related_query_name='contributors_relation', to='issuetracker.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='projects', related_query_name='projects', through='issuetracker.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
